name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          IMAGE="gcr.io/armory-466310/armory:$(date +%s)"
          docker build -t $IMAGE -t gcr.io/armory-466310/armory:latest .
          docker push $IMAGE
          docker push gcr.io/armory-466310/armory:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy armory \
            --image=gcr.io/armory-466310/armory:latest \
            --region=europe-west1 \
            --platform=managed \
            --set-secrets DISCORD_TOKEN=DISCORD_TOKEN:latest \
            --min-instances 1 \
            --quiet